### ISSUE TITLE
Listening redis port

### ISSUE THREAD

**Issue by eribol** [Bunogi/darkredis#10]
Sorry for this question. There was no channel for asking this. 

My question is, i want to listening my redis all the times. Programs should not close. Always keep listening redis port. Can i do that and how?

Ok. İ create simple one.
`let pool = ConnectionPool::create("127.0.0.1:6379".into(), None, num_cpus::get()).await?;

    let server = async move {
        let mut conn = pool.get().await;
        loop {
            let school = conn.get("generates").await;
            match school{
                Ok(s)=>{
                    ///
                },
                Err(e)=>{
                }
            }
            //println!("Accepted connection from ");
                    // TODO: Process socket

        }
    };
    //And away!
    //conn.set("generates", b"behind the bookshelf").await?;
    //let secret_entrance = conn.get("generates").await?;
    //println!("{:?}", String::from_utf8(secret_entrance.unwrap()).unwrap().parse::<i64>().unwrap());

    //Keep our secrets
    //conn.del("secret_entrance").await?;
    println!("Accepted connection from ");
    server.await;
    Ok(())`

**Comment by Bunogi** [comment]
I've set up a [gitter room](https://gitter.im/darkredis/community). Would you mind discussing this there instead?
