### ISSUE TITLE
How to connect a sub address?

### ISSUE THREAD

**Issue by arlicle** [Bunogi/darkredis#18]
addrerss like this: redis://password@172.27.0.10:6379/2

**Comment by Bunogi** [comment]
I assume you mean selecting a database? Unfortunately, there's no way to do that right now.

It would be possible to run the `SELECT` command manually for each connection you use, like this:

```rust
use darkredis::{Connection, Command};

let mut conn = create_connection();
conn.run_command(Command::new("SELECT").arg(b"1)).await?;
```

This is kinda hacky and I think there should be a better way baked into darkredis.
