### ISSUE TITLE
Performance improvement request: provide scratch buffer for serialization

### ISSUE THREAD

**Issue by rw** [Bunogi/darkredis#6]
Calls to `.serialize` end up causing a lot of heap churn. It would be very helpful for users with high performance requirements to be able to control heap allocations in this library. Especially if those allocations occur in tight loops. One way to do this would be to allow users to pass an owned `Vec<u8>` to the command serializer. Another way to do this would be to create a `CommandBuilder` type that serializes commands, and can be reset to a clean state between serializations (this is the approach we take in FlatBuffers).

I'll note that, if serialization can't fail, then it would be even better to not use scratch space at all. Instead, use a Write trait from async-std as the serialization destination.

Cool library, and thanks for working on it!

**Comment by Bunogi** [comment]
Completely on board with this. I'd probably prefer the trait-based method, however that will not guarantee that the buffer is large enough. This means that it'd probably be better to require passing a `&mut Vec<u8>`, to prevent having to handle an extra error. Not sure which would be best.

I feel like adding a new function on `Connection` to execute commands with a previously allocated buffer would be the most ergonomic; the current ones could be changed to wrap this new function.

Thank you for the suggestion, I'll look more into it when I'm done with my exams for the semester.

**Comment by Bunogi** [comment]
0.5.2 improves serialization performance by a lot(cuts the time in half in my own testing), just by writing directly to the output buffer instead of using intermediate buffers. There should be slightly more performance to gain by allowing the re-use of already allocated `Vec<u8>`s though.

**Comment by Bunogi** [comment]
Fixed in 1e07d49
